Algoritmo "ex33"
//          Problema "sequencia_impares" (adaptado de URI 1067)
//Leia um valor inteiro X. Em seguida mostre os ímpares de 1 até X, um
//valor por linha, inclusive o X, se for o caso.
Var
 valor, memoria, contador : inteiro
Inicio
  escreva("Digite o valor de X: ")
  leia(valor)
  
  para contador de 0 ate valor faca
       se contador mod 2 <> 0 entao
          escreval(contador)
       fimse
  fimpara

Fimalgoritmo